name = "TabletWeaving"
uuid = "562db2e1-a68d-468c-8704-31bf85beff7e"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
